## BOW,TFIDF,MACHINE LEARNING ALGORITHM

In [2]:
import numpy as np

np.set_printoptions(threshold=np.inf)

In [3]:
import numpy as np

np.set_printoptions(threshold=np.inf)

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [5]:
import pandas as pd

messages = pd.read_csv('SMSSpamCollection.csv',sep='\t',names=['label','message'])
messages.head()

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [6]:
## data cleaning and preprocessing
import re
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DEV_MANISH\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
wordnetlemmitize = WordNetLemmatizer()

In [8]:
corpus = []

for i in range(0,len(messages)):
    review= re.sub('^[Aa-zA-z]',' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [wordnetlemmitize.lemmatize(word)for word  in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
    

In [9]:
corpus

['jurong point, crazy.. available bugis n great world la e buffet... cine got amore wat...',
 'k lar... joking wif u oni...',
 "ree entry 2 wkly comp win fa cup final tkts 21st may 2005. text fa 87121 receive entry question(std txt rate)t&c's apply 08452810075over18's",
 'dun say early hor... u c already say...',
 'ah think go usf, life around though',
 "reemsg hey darling 3 week's word back! like fun still? tb ok! xxx std chgs send, £1.50 rcv",
 'ven brother like speak me. treat like aid patent.',
 "per request 'melle melle (oru minnaminunginte nurungu vettam)' set callertune callers. press *9 copy friend callertune",
 'inner!! valued network customer selected receivea £900 prize reward! claim call 09061701461. claim code kl341. valid 12 hour only.',
 'ad mobile 11 month more? u r entitled update latest colour mobile camera free! call mobile update co free 08002986030',
 "'m gonna home soon want talk stuff anymore tonight, k? cried enough today.",
 'ix chance win cash! 100 20,000 poun

 ## create Bag of Words

In [10]:
## create bag of wrods
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer( max_features=100)

In [11]:
## independent Feature
X = cv.fit_transform(corpus).toarray()

In [12]:
X

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0

In [13]:
cv.vocabulary_

{'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(92),
 'text': np.int64(79),
 'txt': np.int64(88),
 'say': np.int64(71),
 'already': np.int64(0),
 'think': np.int64(83),
 'go': np.int64(21),
 'life': np.int64(37),
 'week': np.int64(94),
 'back': np.int64(3),
 'like': np.int64(38),
 'still': np.int64(75),
 'ok': np.int64(58),
 'send': np.int64(73),
 'me': np.int64(43),
 'friend': np.int64(18),
 'prize': np.int64(66),
 'claim': np.int64(8),
 'call': np.int64(4),
 'mobile': np.int64(48),
 'free': np.int64(17),
 'co': np.int64(9),
 'home': np.int64(29),
 'want': np.int64(91),
 'today': np.int64(85),
 'cash': np.int64(7),
 'day': np.int64(12),
 'reply': np.int64(68),
 'no': np.int64(55),
 'www': np.int64(98),
 'right': np.int64(69),
 'take': np.int64(77),
 'message': np.int64(45),
 'make': np.int64(42),
 'that': np.int64(80),
 'way': np.int64(93),
 'dont': np.int64(14),
 'miss': np.int64(47),
 'ur': np.int64(90),
 'going': np.int64(22),
 'da': np.int64(11),
 'lor': np.int64(39

In [14]:
y = pd.get_dummies(messages['label'], dtype=int)

y = y.iloc[:, 0].values

In [15]:
y

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,

In [16]:
## train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [17]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train,y_train)

In [18]:
y_pred = spam_detect_model.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[119  30]
 [ 13 953]]
0.9614349775784753
              precision    recall  f1-score   support

           0       0.90      0.80      0.85       149
           1       0.97      0.99      0.98       966

    accuracy                           0.96      1115
   macro avg       0.94      0.89      0.91      1115
weighted avg       0.96      0.96      0.96      1115



## Creating the TF-IDF Model

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer(max_features=2500,ngram_range=(1,2))

X = tv.fit_transform(corpus).toarray()

In [22]:
tv.vocabulary_

{'point': np.int64(1712),
 'crazy': np.int64(562),
 'available': np.int64(269),
 'bugis': np.int64(366),
 'great': np.int64(941),
 'world': np.int64(2450),
 'la': np.int64(1169),
 'cine': np.int64(476),
 'got': np.int64(932),
 'wat': np.int64(2362),
 'lar': np.int64(1179),
 'joking': np.int64(1139),
 'wif': np.int64(2414),
 'ree': np.int64(1798),
 'entry': np.int64(734),
 'wkly': np.int64(2435),
 'comp': np.int64(520),
 'win': np.int64(2420),
 'cup': np.int64(574),
 'final': np.int64(802),
 'may': np.int64(1333),
 'text': np.int64(2119),
 'receive': np.int64(1790),
 'question': np.int64(1756),
 'std': np.int64(2042),
 'txt': np.int64(2227),
 'rate': np.int64(1769),
 'apply': np.int64(230),
 'ree entry': np.int64(1800),
 'txt rate': np.int64(2231),
 'rate apply': np.int64(1770),
 'dun': np.int64(681),
 'say': np.int64(1884),
 'early': np.int64(693),
 'already': np.int64(200),
 'ah': np.int64(184),
 'think': np.int64(2140),
 'go': np.int64(903),
 'usf': np.int64(2298),
 'life': np.int64(

In [23]:
#3 train test and split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [24]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train,y_train)

In [25]:
y_pred = spam_detect_model.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[131  18]
 [  2 964]]
0.9820627802690582
              precision    recall  f1-score   support

           0       0.98      0.88      0.93       149
           1       0.98      1.00      0.99       966

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

